---
AWSTemplateFormatVersion: '2010-09-09'
Description: "Provision the Damn Vulnerable Cloud Application's Frontend"

Parameters:
  DomainName:
    Type: String

Conditions:
  DomainNameSpecified:
    !Not [!Equals [!Ref DomainName, '']]

Resources:
  DVCAFrontendBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !If [DomainNameSpecified, !Ref DomainName, dvca-frontend-bucket]
      WebsiteConfiguration:
        IndexDocument: index.html

  DVCAFrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DVCAFrontendBucket
      PolicyDocument:
        Version: '2008-10-17'
        Statement:
        - Sid: DVCAFrontendBucketPolicy
          Effect: Allow
          Principal: '*'
          Action:
          - s3:GetObject
          Resource:
          - !Sub arn:aws:s3:::${DVCAFrontendBucket}/*
